# Generated by Django 5.1.1 on 2024-10-03 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='title',
            field=models.CharField(default='Reviews Title', max_length=255),
        ),
        migrations.AlterField(
            model_name='reviewimage',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='review_images/'),
        ),
    ]
