# Generated by Django 5.1.1 on 2024-10-03 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_review_title_alter_reviewimage_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='price_range',
            field=models.CharField(choices=[('LOW', 'ราคาต่ำกว่า 100 บาท'), ('MEDIUM', 'ราคามากกว่า 100 บาท'), ('HIGH', 'ราคามากกว่า 500 บาท'), ('PREMIUM', 'ราคามากกว่า 1,000 บาท')], max_length=20),
        ),
    ]
