# Generated by Django 5.1.1 on 2024-10-03 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_restaurant_price_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='phone_number',
            field=models.CharField(default='Unknown', max_length=15),
        ),
    ]
